#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3g
kotlin.incremental=true

#Gradle
org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon.idletimeout=1800000
org.gradle.configuration-cache=true

#Kotlin/Native
kotlin.native.ignoreDisabledTargets=true

#Android
android.nonTransitiveRClass=true