package com.oak.app.ui.settings

import androidx.compose.runtime.Immutable
import com.oak.app.data.ImportSection
import com.oak.app.data.OakFontFamily
import com.oak.app.data.Service
import com.oak.app.data.ThemeMode
import com.oak.app.inference.LocalModel
import com.oak.app.mcp.PopularMcpServer
import com.oak.app.ssh.SshAuthType

@Immutable
data class SettingsActions(
    val onSelectTab: (SettingsTab) -> Unit,
    val onAddService: (Service) -> Unit,
    val onRemoveService: (String) -> Unit,
    val onReorderServices: (List<String>) -> Unit,
    val onExpandService: (String?) -> Unit,
    val onChangeApiKey: (String, String) -> Unit,
    val onChangeBaseUrl: (String, String) -> Unit,
    val onSelectModel: (String, String) -> Unit,
    val onToggleTool: (String, Boolean) -> Unit,
    val onSaveSoul: (String) -> Unit,
    val onToggleDynamicUi: (Boolean) -> Unit,
    val onChangeThemeMode: (ThemeMode) -> Unit,
    val onChangeFontFamily: (OakFontFamily) -> Unit,
    val onChangeAiFontFamily: (OakFontFamily) -> Unit,
    val onToggleDynamicColors: (Boolean) -> Unit,
    val onToggleMemory: (Boolean) -> Unit,
    val onDeleteMemory: (String) -> Unit,
    val onUpdateMemory: (String, String) -> Unit,
    val onToggleScheduling: (Boolean) -> Unit,
    val onCancelTask: (String) -> Unit,
    val onToggleDaemon: (Boolean) -> Unit,
    val onToggleHeartbeat: (Boolean) -> Unit,
    val onChangeHeartbeatInterval: (Int) -> Unit,
    val onChangeHeartbeatActiveHours: (Int, Int) -> Unit,
    val onSaveHeartbeatPrompt: (String) -> Unit,
    val onChangeHeartbeatService: (String?) -> Unit,
    val onRefreshHeartbeat: () -> Unit,
    val onToggleEmail: (Boolean) -> Unit,
    val onRemoveEmailAccount: (String) -> Unit,
    val onChangeEmailPollInterval: (Int) -> Unit,
    val onRefreshEmailAccount: (String) -> Unit,
    val onToggleSms: (Boolean) -> Unit,
    val onChangeSmsPollInterval: (Int) -> Unit,
    val onRefreshSms: () -> Unit,
    val onToggleSmsSend: (Boolean) -> Unit,
    val onToggleNotifications: (Boolean) -> Unit,
    val onOpenNotificationListenerSettings: () -> Unit,
    val onClearPendingNotifications: () -> Unit,
    val onToggleStreaming: (Boolean) -> Unit,
    val onToggleUnlimitedToolCalls: (Boolean) -> Unit,
    val onChangeUiScale: (Float) -> Unit,
    val onAddMcpServer: (String, String, Map<String, String>) -> Unit,
    val onRemoveMcpServer: (String) -> Unit,
    val onToggleMcpServer: (String, Boolean) -> Unit,
    val onRefreshMcpServer: (String) -> Unit,
    val onShowAddMcpServerDialog: (Boolean) -> Unit,
    val onAddPopularMcpServer: (PopularMcpServer) -> Unit,
    val onAddSshServer: (String, String, Int, String, String, String, String, SshAuthType) -> Unit,
    val onRemoveSshServer: (String) -> Unit,
    val onToggleSshServer: (String, Boolean) -> Unit,
    val onConnectSshServer: (String) -> Unit,
    val onShowAddSshServerDialog: (Boolean) -> Unit,
    val onToggleSkill: (String, Boolean) -> Unit,
    val onRemoveSkill: (String) -> Unit,
    val onImportSkill: (String, String, String, List<String>) -> Unit,
    val onShowImportSkillDialog: (Boolean) -> Unit,
    val onImportSkillFromFile: () -> Unit,
    val onSkillFilePicked: (ByteArray, String) -> Unit,
    val onEditSkill: (String, String, String, String, List<String>) -> Unit,
    val onShowEditSkillDialog: (String?) -> Unit,
    val onResetSkill: (String) -> Unit,
    val onDownloadLocalModel: (LocalModel) -> Unit,
    val onCancelLocalModelDownload: () -> Unit,
    val onDeleteLocalModel: (String) -> Unit,
    val onChangeModelContextTokens: (String, Int) -> Unit,
    val onChangeBackendPreference: (String) -> Unit,
    val onExportSettings: (Set<ImportSection>) -> String,
    val onPrepareExport: () -> Map<ImportSection, String?>,
    val onImportSettings: (ByteArray, Set<ImportSection>, Boolean) -> ImportResult,
    val onToggleStorageAccess: (Boolean) -> Unit,
    val onUndoDelete: () -> Unit,
) {
    companion object {
        val NoOp = SettingsActions(
            onSelectTab = {},
            onAddService = {},
            onRemoveService = {},
            onReorderServices = {},
            onExpandService = {},
            onChangeApiKey = { _, _ -> },
            onChangeBaseUrl = { _, _ -> },
            onSelectModel = { _, _ -> },
            onToggleTool = { _, _ -> },
            onSaveSoul = {},
            onToggleDynamicUi = {},
            onChangeThemeMode = {},
            onChangeFontFamily = {},
            onChangeAiFontFamily = {},
            onToggleDynamicColors = {},
            onToggleMemory = {},
            onDeleteMemory = {},
            onUpdateMemory = { _, _ -> },
            onToggleScheduling = {},
            onCancelTask = {},
            onToggleDaemon = {},
            onToggleHeartbeat = {},
            onChangeHeartbeatInterval = {},
            onChangeHeartbeatActiveHours = { _, _ -> },
            onSaveHeartbeatPrompt = {},
            onChangeHeartbeatService = {},
            onRefreshHeartbeat = {},
            onToggleEmail = {},
            onRemoveEmailAccount = {},
            onChangeEmailPollInterval = {},
            onRefreshEmailAccount = {},
            onToggleSms = {},
            onChangeSmsPollInterval = {},
            onRefreshSms = {},
            onToggleSmsSend = {},
            onToggleNotifications = {},
            onOpenNotificationListenerSettings = {},
            onClearPendingNotifications = {},
            onToggleStreaming = {},
            onToggleUnlimitedToolCalls = {},
            onChangeUiScale = {},
            onAddMcpServer = { _, _, _ -> },
            onRemoveMcpServer = {},
            onToggleMcpServer = { _, _ -> },
            onRefreshMcpServer = {},
            onShowAddMcpServerDialog = {},
            onAddPopularMcpServer = {},
            onAddSshServer = { _, _, _, _, _, _, _, _ -> },
            onRemoveSshServer = {},
            onToggleSshServer = { _, _ -> },
            onConnectSshServer = {},
            onShowAddSshServerDialog = {},
            onToggleSkill = { _, _ -> },
            onRemoveSkill = {},
            onImportSkill = { _, _, _, _ -> },
            onShowImportSkillDialog = {},
            onImportSkillFromFile = {},
            onSkillFilePicked = { _, _ -> },
            onEditSkill = { _, _, _, _, _ -> },
            onShowEditSkillDialog = {},
            onResetSkill = {},
            onDownloadLocalModel = {},
            onCancelLocalModelDownload = {},
            onDeleteLocalModel = {},
            onChangeModelContextTokens = { _, _ -> },
            onChangeBackendPreference = {},
            onExportSettings = { _ -> "" },
            onPrepareExport = { emptyMap() },
            onImportSettings = { _, _, _ -> ImportResult.Failure },
            onToggleStorageAccess = {},
            onUndoDelete = {},
        )
    }
}
